### ISSUE TITLE
Add logic for authorized topics and users

### ISSUE THREAD

**Issue by rpelisse** [ansible-middleware/amq_streams#10]
##### SUMMARY

Wrappers to create users and authorize topics are provided by the project, they need to be wrapped properly and tested within the molecule test suite to ensure those features are properly exposed through the collection.

##### ISSUE TYPE
 - Feature Idea

**Comment by rpelisse** [comment]
Partially fixed by https://github.com/ansible-middleware/amq_streams/pull/60

**Comment by rpelisse** [comment]
@rmarting What are we missing here? Maybe just a wrapper around kafka-acl? Anything else?

**Comment by rmarting** [comment]
@rpelisse This issue is related to #64, as the `kafka-acl.sh` script only works when authorization is enabled. Now we have only the creation of users in an authenticated broker, but not managing the authorization policies. As soon the #64 is closed, we can extend this one to manage the authorization policies between users and topics.

**Comment by rpelisse** [comment]
For clarity purpose, let's close this issue and only keep #64. I'm planning to work on #64 this week anyway.
