### ISSUE TITLE
Enable Broker Authentication

### ISSUE THREAD

**Issue by rmarting** [ansible-middleware/amq_streams#34]
##### SUMMARY

By default BK exposes the services without any kind of authentication mechanism allowing to any user to manage topics, and to publish/consume messages. It is a good practice to enable authentication as an initial step of a more secure kafka cluster.

The `amq_streams_broker` role must allow to enable this capability provided by Kafka.

Reference:

* [Broker Authtentication](https://access.redhat.com/documentation/en-us/red_hat_amq_streams/2.4/html-single/using_amq_streams_on_rhel/index#con-kafka-securing-listeners-str)

##### ISSUE TYPE
 - Feature Idea

**Comment by rmarting** [comment]
I am not sure if we can close this issue, as the latest PR relates to Authentication implements it. However, there are some extra authentication mechanisms not already implemented (e.g. client certificates), so they could be part of this issue.

Should we open an issue for each specific authentication mechanism? Or should we use this one? @rpelisse What do you think?

**Comment by rpelisse** [comment]
Without going to much into semantics, this issue was about enabling authentification, which I think, thanks to your work, we have (at least) partially done that. So, for the sake of keeping it simple and avoid the anti-pattern of having an issue remaining opens "forever", I would suggest we close this one as resolved.

For the next part, however, I don't think we should open one issue by auth mec, but maybe a few. If there is, for instance, two or three mechanism that should be somewhat easy to implement, let's group them into one issue. And maybe open another one for the more complex implementation?

WDYT?

**Comment by rmarting** [comment]
Ok, it makes sense to have specific issues for each extra authentication or authorization capabilities of the collection. It will help us to track each of them, and avoid to have an EPIC :smile: about Auth/Authz. 

So, IMHO we can close this one as we have almost the most important topics about authentication.
